name: edmo
x-podman:
    in_pod: false # We only have a single container, having a cluster/pod is overkill
services:
    sim_cf:
        container_name: edmo
        hostname: edmo
        image: edmo
        # We want interactivity in this container
        stdin_open: true
        tty: true
        ports:
            - "8080:8080"
            
        build:
            context: .
            dockerfile: containerfile

        volumes:
            # We need arbitrary tty access
            # Be sure to add udev rules to allow everyone to rw to the relevant tty files
            #  - A sample udev rule is provided alongside this compose file
            - /dev:/dev:rw
            - ${HOME}/Source/EDMO/ServerVNext:/root/Source/ServerVNext:rw
            - ${HOME}/Source/EDMO/ArduinoFirmware:/root/Source/ArduinoFirmware:rw

        security_opt:
            - label=type:container_runtime_t
